apiVersion: v1
kind: Service
metadata:
  name: otd-OTD_MSA_Back_Life
  namespace: app
  labels:
    app: otd-OTD_MSA_Back_Life
spec:
  selector:
    app: otd-OTD_MSA_Back_Life
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP